import type { NextPage, GetServerSideProps } from 'next'

import Head from 'next/head'
import Presentation from '../components/home/presentation'
import Projects from '../components/home/projects'
import styles from '../styles/Home.module.scss'

const Home: NextPage = ({projects}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio-landing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
       <Presentation/>
       <Projects projects={projects}/>
      </main>
    </div>
  )
}

export default Home


export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch('https://my-json-server.typicode.com/matifandy8/nextjs-portfolio/projects');
  const data = await res.json();
  console.log(data)


  return {
    props: { projects: data },
  };
};
