import type { NextPage } from 'next'
import Head from 'next/head'
import Presentation from '../components/home/presentation'
import Projects from '../components/home/projects'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio-landing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
       <Presentation/>
       <Projects/>
      </main>
    </div>
  )
}

export default Home
